config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get "home/blog"
  get "home/about"
  get "home/contact"
  get "home/coming_soon"

  resources :writings
  namespace :admin do
    root 'home#index'
    resources :writings
  end

  mount Ckeditor::Engine => '/ckeditor'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/active_storage.rb
module Ckeditor
  module ActiveStorage
    def self.included(base)
      base.send(:include, InstanceMethods)
      base.send(:extend, ClassMethods)
    end

    module ClassMethods
      def self.extended(base)
        base.class_eval do
          before_validation :apply_data
        end
      end
    end

    module InstanceMethods
      protected

      def file
        @file ||= data
      end

      def blob
        @blob ||= ::ActiveStorage::Blob.find(file.attachment.blob_id)
      end

      def apply_data
        self.data_file_name = blob.filename
        self.data_content_type = blob.content_type
        self.data_file_size = blob.byte_size
      end
    end
  end
end

app/models/ckeditor/asset.rb
# class Ckeditor::Asset < ActiveRecord::Base
#   include Ckeditor::Orm::ActiveRecord::AssetBase
#   include Ckeditor::Backend::Paperclip
# end
require 'active_storage'

module Ckeditor
  class Asset < ActiveRecord::Base
    include Ckeditor::Orm::ActiveRecord::AssetBase
    include Ckeditor::ActiveStorage
  end
end

app/models/ckeditor/attachment_file.rb
# class Ckeditor::AttachmentFile < Ckeditor::Asset
#   has_attached_file :data,
#                     url: '/ckeditor_assets/attachments/:id/:filename',
#                     path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

#   validates_attachment_presence :data
#   validates_attachment_size :data, less_than: 100.megabytes
#   do_not_validate_attachment_file_type :data

#   def url_thumb
#     @url_thumb ||= Ckeditor::Utils.filethumb(filename)
#   end
# end

app/models/ckeditor/picture.rb
# class Ckeditor::Picture < Ckeditor::Asset
#   has_attached_file :data,
#                     url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
#                     path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
#                     styles: { content: '800>', thumb: '118x100#' }

#   validates_attachment_presence :data
#   validates_attachment_size :data, less_than: 2.megabytes
#   validates_attachment_content_type :data, content_type: /\Aimage/

#   def url_content
#     url(:content)
#   end
# end

module Ckeditor
  class Picture < Asset
    include Rails.application.routes.url_helpers

    has_one_attached :data

    def url_content
      rails_blob_url(blob)
    end

    class << self
      def default_url_options
        Rails.application.config.action_mailer.default_url_options
      end
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :rememberable, :trackable, :validatable
  # :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable
  # has_many :writings
end

app/models/writing.rb
class Writing < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  # belongs_to :user
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base

  layout 'admin'
  before_action :authenticate_user!
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController

  def index
    @contacts = Contact.all.order(updated_at: :desc)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    #@contact.user = current_user
    respond_to do |format|
      if @contact.save
        format.html { redirect_to admin_contacts_path, notice: '新增文章成功' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to admin_contacts_url
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController

  def index
    
  end



end

app/controllers/admin/writings_controller.rb
class Admin::WritingsController < Admin::ApplicationController
  before_action :set_writing, only: [:show, :edit, :update, :destroy]

  def index
    @writings = Writing.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @writing = Writing.find(params[:id])
  end

  def new
    @writing = Writing.new
  end

  def create
    @writing = Writing.new(writing_params)
    #@writing.user = current_user
    respond_to do |format|
      if @writing.save
        format.html { redirect_to admin_writings_path, notice: '新增文章成功' }
        format.json { render :show, status: :created, location: @writing }
      else
        format.html { render :new }
        format.json { render json: @writing.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @writing = Writing.find(params[:id]) 
  end

  def update
    respond_to do |format|
      if @writing.update(writing_params)
        format.html { redirect_to admin_writings_path, notice: '更新文章成功' }
        format.json { render :show, status: :ok, location: @writing }
      else
        format.html { render :edit }
        format.json { render json: @writing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @writing = Writing.find(params[:id])
    @writing.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_writings_url }
      format.json { head :no_content }
    end
  end

private

  def set_writing
    @writing = Writing.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def writing_params
    params.require(:writing).permit(:title , :description ,:writer, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @writings = Writing.order(created_at: :desc).page(params[:page]).per(6)
  end

  def about
      
  end  

  def contact

  end

  def coming_soon
    
  end

private


end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  before_action :set_writing, only: [:show]
  
  def show
    @writing = Writing.find(params[:id])
  end

private

  def set_writing
    @writing = Writing.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def writing_params
    params.require(:writing).permit(:title , :description ,:writer, :image)
  end

end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/writings_helper.rb
module Admin::WritingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/writings_helper.rb
module WritingsHelper
end

app/views/admin/home/index.html.erb
<h3>後台首頁</h3> 

app/views/admin/writings/_form.html.erb
<div class="writing_form">
  <div class="col-md-10">
    <%= form_for [:admin, @writing] do |f| %>
      <% if @writing.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@writing.errors.count, "error") %> prohibited this writing from being saved:</h2>

          <ul>
          <% @writing.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label '標題' %><br>
        <%= f.text_field :title, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label '作者' %><br>
        <%= f.text_field :writer, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label '內容' %><br>
        <%= f.cktext_area :description, :class => "form-control" , :ckeditor => {:toolbar => 'mini'}%>
      </div>
      <div class="form-group">
        <%= f.label '文章圖片' %><br>
        <%= f.file_field :image %>
      </div>
      <div class="actions">
        <%= f.submit 'submit', :class => "btn btn-primary btn-full" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/writings/edit.html.erb
<%= render "form" %>

app/views/admin/writings/index.html.erb
<h3>部落格管理<%= link_to '新增文章', new_admin_writing_path, :class => 'btn btn-success' %></h3>

<table class="table">
  <thead>
    <tr>
      <th>標題</th>
      <th>作者</th>
      <th>內容</th>
      <th>日期</th>
      <th></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @writings.each do |writing| %>
      <tr>
        <td><%= writing.title %></td>
        <!-- <td><%#= writing.user.id %></td> -->
        <td><%= writing.writer %></td>
        <td><em><%= time_ago_in_words(writing.created_at) %> ago -</em></td>
        <td><%= simple_format(writing.description.truncate(100)) %></td>
        <td>
          <div class="home_index"> 
          <% if writing.image.attached? %> 
            <%= image_tag(writing.image) %>
            <% else %>
            無照片
          <% end %> 
          </div> 
        </td>
        <td><%= link_to '編輯', edit_admin_writing_path(writing), :class => "btn btn-info" %></td>
        <td><%= link_to '刪除', admin_writing_path(writing), method: :delete, data: { confirm: '確定要刪除?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
    <%= paginate @writings %>
  </tbody>
</table>

app/views/admin/writings/new.html.erb
<%= render "form" %>

app/views/home/about.html.erb
<nav id="nav">
  <ul class="links">
    <li><%= link_to '文章首頁' ,root_path %></li>
    <li class="active"><%= link_to "關於我們", home_about_path %></li>
    <li><%= link_to "聯絡我們", home_contact_path %></li>
    <li><%= link_to "語言百科", home_coming_soon_path %></li>
  </ul>
  <ul class="icons">
    <li><a href="#" class="icon fa fa-twitter"></a></li>
    <li><a href="#" class="icon fa fa-facebook"></a></li>
    <li><a href="#" class="icon fa fa-instagram"></a></li>
  </ul>
</nav>

<!-- Main -->
<div id="main">

  <!-- Post -->
    <section class="post">
      <header class="major">
        <span class="date">June 13, 2018</span>
        <h1>I-M HERE 商業X語言</h1>
        <p>我們都有個想一展長才的夢想，我們都想創造屬於自己的一片天空</p>
      </header>
      <div class="image main"><img src="images/pic01.jpg" alt="" /></div>
      <p>Isla和Mia平常就很喜歡充實自己的商業知識，同時也很熱衷於語言學習，想說既然都學那麼多了，不如整理一下腦袋裡蒐集到的資料，並分享給大家~非常希望我們能幫上大家的忙，也希望能和大家一起交流、變成好朋友 💗💗</p>
      <p>你的每次留言都對Isla、Mia來說都是滿滿的動力💪💪害羞的朋友也歡迎私訊我們~一起來研究、切磋吧🤝</p>
      <p>如果覺得我們的網站對你有幫助的話，請留下評論吧~~寫越多我們越開心~~~😘😘😘</p>
    </section>

</div>

app/views/home/coming_soon.html.erb
<nav id="nav">
  <ul class="links">
    <li><%= link_to '文章首頁' ,root_path %></li>
    <li><%= link_to "關於我們", home_about_path %></li>
    <li><%= link_to "聯絡我們", home_contact_path %></li>
    <li><%= link_to "語言百科", home_coming_soon_path %></li>
  </ul>
  <ul class="icons">
    <li><a href="#" class="icon fa fa-twitter"></a></li>
    <li><a href="#" class="icon fa fa-facebook"></a></li>
    <li><a href="#" class="icon fa fa-instagram"></a></li>
  </ul>
</nav>
<div id="main">

  <article class="post featured">
    <header class="major">
      <span class="date"></span>
      <h2>Coming Soon!</h2>
      <p>這個頁面功能仍在測試中，敬請期待!</p>
    </header>
    <a class="image main"><img src="<%= asset_path 'wrapper1.png'%>" alt="" /></a>
  </article>


</div>

app/views/home/contact.html.erb
<nav id="nav">
  <ul class="links">
    <li><%= link_to '文章首頁' ,root_path %></li>
    <li><%= link_to "關於我們", home_about_path %></li>
    <li class="active"><%= link_to "聯絡我們", home_contact_path %></li>
    <li><%= link_to "語言百科", home_coming_soon_path %></li>
  </ul>
  <ul class="icons">
    <li><a href="#" class="icon fa fa-twitter"></a></li>
    <li><a href="#" class="icon fa fa-facebook"></a></li>
    <li><a href="#" class="icon fa fa-instagram"></a></li>
  </ul>
</nav>
<!-- Footer -->
<footer id="footer">
  <section>
    <%#= form_for @contact do |f| %>
      <div class="field">
        <label for="name">Name</label>
        <%= text_field :name, :required => true , placeholder: "姓名" , class: "form-input", id: "contact-first-name" ,  type:"text" , name: "name" %>
      </div>
      <div class="field">
        <label for="email">Email</label>
        <input type="text" name="email" id="email" />
      </div>
      <div class="field">
        <label for="message">Message</label>
        <textarea name="message" id="message" rows="3"></textarea>
      </div>
      <ul class="actions">
        <li><input type="submit" value="Send Message" /></li>
      </ul>
    <%# end %>
  </section>
  <section class="split contact">
    <section class="alt">
      <h3>Address</h3>
      <p></p>
    </section>
    <section>
      <h3>Phone</h3>
      <p><a href="#">(000) 000-0000</a></p>
    </section>
    <section>
      <h3>Email</h3>
      <p><a href="#">imhere20180428@gmail.com</a></p>
    </section>
    <section>
      <h3>Social</h3>
      <ul class="icons alt">
        <li><a href="#" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
        <li><a href="#" class="icon alt fa-instagram"><span class="label">Instagram</span></a></li>
      </ul>
    </section>
  </section>
</footer>

app/views/home/index.html.erb
<!-- Wrapper -->
    <nav id="nav">
      <ul class="links">
        <li class="active"><%= link_to '文章首頁' ,root_path %></li>
        <li><%= link_to "關於我們", home_about_path %></li>
        <li><%= link_to "聯絡我們", home_contact_path %></li>
        <li><%= link_to "語言百科", home_coming_soon_path %></li>
      </ul>
      <ul class="icons">
        <li><a href="#" class="icon fa fa-twitter"></a></li>
        <li><a href="#" class="icon fa fa-facebook"></a></li>
        <li><a href="#" class="icon fa fa-instagram"></a></li>
      </ul>
    </nav>



<div id="main">
<!--   <article class="post featured">
    <header class="major">
      <span class="date">April 25, 2017</span>
      <h2><a href="#">And this is a<br />
      massive headline</a></h2>
      <p>Aenean ornare velit lacus varius enim ullamcorper proin aliquam<br />
      facilisis ante sed etiam magna interdum congue. Lorem ipsum dolor<br />
      amet nullam sed etiam veroeros.</p>
    </header>
    <a href="#" class="image main"><img src="<%= asset_path 'pic01.jpg'%>" alt="" /></a>
    <ul class="actions">
      <li><a href="#" class="button big">Full Story</a></li>
    </ul>
  </article> -->

  <section class="posts">
    <% @writings.each do |writing| %>
      <article>
        <header>
          <span class="date"><%= time_ago_in_words(writing.created_at) %> ago</span>
          <h2><a href="#"><%= link_to writing.title , writing_path(writing) %></h2>
        </header>
        <%= link_to writing_path(writing) do %>
          <div class="image fit home_index">
            <% if writing.image.attached? %>
              <%= image_tag(writing.image) %>
              <% else %>
              <img src="<%= asset_path 'pic02.jpg' %>" alt="" />
            <% end %>
          </div>
        <% end %>
        <p><%= simple_format(writing.description.truncate(100)) %></p>
        <ul class="actions">
          <li><%= link_to "Full Story" , writing_path(writing) , class: "button" %></li>
        </ul>
      </article>
    <% end %>
    <% if @writings.count % 2 != 0 %>
      <article>
      </article>
    <% end %>
<!--     <article>
      <header>
        <span class="date">April 22, 2017</span>
        <h2><a href="#">Primis eget<br />
        imperdiet lorem</a></h2>
      </header>
      <a href="#" class="image fit"><img src="<%= asset_path "pic03.jpg" %>" alt="" /></a>
      <p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis magna etiam.</p>
      <ul class="actions">
        <li><a href="#" class="button">Full Story</a></li>
      </ul>
    </article> -->
  </section>

  <footer>
    <div class="pagination">
      <%= paginate @writings %>
<!--       <a href="#" class="previous">Prev</a>
      <a href="#" class="page active">1</a>
      <a href="#" class="page">2</a>
      <a href="#" class="page">3</a>
      <span class="extra">&hellip;</span>
      <a href="#" class="page">8</a>
      <a href="#" class="page">9</a>
      <a href="#" class="page">10</a>
      <a href="#" class="next">Next</a> -->
    </div>
  </footer>

</div>

  <!-- Footer -->
    <footer id="footer">
      <section>
        <form method="post" action="#">
          <div class="field">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" />
          </div>
          <div class="field">
            <label for="email">Email</label>
            <input type="text" name="email" id="email" />
          </div>
          <div class="field">
            <label for="message">Message</label>
            <textarea name="message" id="message" rows="3"></textarea>
          </div>
          <ul class="actions">
            <li><input type="submit" value="Send Message" /></li>
          </ul>
        </form>
      </section>
      <section class="split contact">
        <section class="alt">
          <h3>Address</h3>
          <p></p>
        </section>
        <section>
          <h3>Phone</h3>
          <p><a href="#">(000) 000-0000</a></p>
        </section>
        <section>
          <h3>Email</h3>
          <p><a href="#">imhere20180428@gmail.com</a></p>
        </section>
        <section>
          <h3>Social</h3>
          <ul class="icons alt">
            <li><a href="#" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon alt fa-instagram"><span class="label">Instagram</span></a></li>
          </ul>
        </section>
      </section>
    </footer>

app/views/writings/show.html.erb
<nav id="nav">
  <ul class="links">
    <li><%= link_to '文章首頁' ,root_path %></li>
    <li><%= link_to "關於我們", home_about_path %></li>
    <li><%= link_to "聯絡我們", home_contact_path %></li>
    <li><%= link_to "語言百科", home_coming_soon_path %></li>
  </ul>
  <ul class="icons">
    <li><a href="#" class="icon fa fa-twitter"></a></li>
    <li><a href="#" class="icon fa fa-facebook"></a></li>
    <li><a href="#" class="icon fa fa-instagram"></a></li>
  </ul>
</nav>

<!-- Main -->

<div id="main">

  <section class="post" style="width: 80%;text-align: center;margin-left: auto;
    margin-right: auto;">
    <header class="major">
      <span class="date"><%= time_ago_in_words(@writing.created_at) %> ago</span>
      <h3 style="font-size: 25px;"><%= @writing.title %></h3>
    </header>
    <div class="image main">
      <% if @writing.image.attached? %>
        <%= image_tag(@writing.image) %>
        <% else %>
        <img src="<%= asset_path 'pic01.jpg' %>" alt="" />
      <% end %>
    </div>
    <p><%= raw(@writing.description) %></p>
    <div class="writer_profile col-md-12" style="background-color: gray;">
      <div class="left col-md-6"><%= @writing.writer %></div>
      <div class="right col-md-6">fjivjdfp</div>
    </div>
  </section>


</div>