config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get "home/blog"
  get "home/about"
  get "home/contact"
  get "home/coming_soon"

  resources :writings
  namespace :admin do
    root 'home#index'
    resources :writings
  end

  mount Ckeditor::Engine => '/ckeditor'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/active_storage.rb
module Ckeditor
  module ActiveStorage
    def self.included(base)
      base.send(:include, InstanceMethods)
      base.send(:extend, ClassMethods)
    end

    module ClassMethods
      def self.extended(base)
        base.class_eval do
          before_validation :apply_data
        end
      end
    end

    module InstanceMethods
      protected

      def file
        @file ||= data
      end

      def blob
        @blob ||= ::ActiveStorage::Blob.find(file.attachment.blob_id)
      end

      def apply_data
        self.data_file_name = blob.filename
        self.data_content_type = blob.content_type
        self.data_file_size = blob.byte_size
      end
    end
  end
end

app/models/ckeditor/asset.rb
# class Ckeditor::Asset < ActiveRecord::Base
#   include Ckeditor::Orm::ActiveRecord::AssetBase
#   include Ckeditor::Backend::Paperclip
# end
require 'active_storage'

module Ckeditor
  class Asset < ActiveRecord::Base
    include Ckeditor::Orm::ActiveRecord::AssetBase
    include Ckeditor::ActiveStorage
  end
end

app/models/ckeditor/attachment_file.rb
# class Ckeditor::AttachmentFile < Ckeditor::Asset
#   has_attached_file :data,
#                     url: '/ckeditor_assets/attachments/:id/:filename',
#                     path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

#   validates_attachment_presence :data
#   validates_attachment_size :data, less_than: 100.megabytes
#   do_not_validate_attachment_file_type :data

#   def url_thumb
#     @url_thumb ||= Ckeditor::Utils.filethumb(filename)
#   end
# end

app/models/ckeditor/picture.rb
# class Ckeditor::Picture < Ckeditor::Asset
#   has_attached_file :data,
#                     url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
#                     path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
#                     styles: { content: '800>', thumb: '118x100#' }

#   validates_attachment_presence :data
#   validates_attachment_size :data, less_than: 2.megabytes
#   validates_attachment_content_type :data, content_type: /\Aimage/

#   def url_content
#     url(:content)
#   end
# end

module Ckeditor
  class Picture < Asset
    include Rails.application.routes.url_helpers

    has_one_attached :data

    def url_content
      rails_blob_url(blob)
    end

    class << self
      def default_url_options
        Rails.application.config.action_mailer.default_url_options
      end
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :rememberable, :trackable, :validatable
  # :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :trackable, :validatable
  # has_many :writings
end

app/models/writing.rb
class Writing < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  # belongs_to :user
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController

  def index
    @contacts = Contact.all.order(updated_at: :desc)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    #@contact.user = current_user
    respond_to do |format|
      if @contact.save
        format.html { redirect_to admin_contacts_path, notice: '新增文章成功' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to admin_contacts_url
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController

  def index
    
  end



end

app/controllers/admin/writings_controller.rb
class Admin::WritingsController < Admin::ApplicationController
  before_action :set_writing, only: [:show, :edit, :update, :destroy]

  def index
    @writings = Writing.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @writing = Writing.find(params[:id])
  end

  def new
    @writing = Writing.new
  end

  def create
    @writing = Writing.new(writing_params)
    #@writing.user = current_user
    respond_to do |format|
      if @writing.save
        format.html { redirect_to admin_writings_path, notice: '新增文章成功' }
        format.json { render :show, status: :created, location: @writing }
      else
        format.html { render :new }
        format.json { render json: @writing.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @writing = Writing.find(params[:id]) 
  end

  def update
    respond_to do |format|
      if @writing.update(writing_params)
        format.html { redirect_to admin_writings_path, notice: '更新文章成功' }
        format.json { render :show, status: :ok, location: @writing }
      else
        format.html { render :edit }
        format.json { render json: @writing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @writing = Writing.find(params[:id])
    @writing.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_writings_url }
      format.json { head :no_content }
    end
  end

private

  def set_writing
    @writing = Writing.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def writing_params
    params.require(:writing).permit(:title , :description ,:writer, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @writings = Writing.order(created_at: :desc).page(params[:page]).per(6)
  end

  def about
      
  end  

  def contact

  end

  def coming_soon
    
  end

private


end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  before_action :set_writing, only: [:show]
  
  def show
    @writing = Writing.find(params[:id])
  end

private

  def set_writing
    @writing = Writing.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def writing_params
    params.require(:writing).permit(:title , :description ,:writer, :image)
  end

end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/writings_helper.rb
module Admin::WritingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/writings_helper.rb
module WritingsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I-M HERE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <!-- <link rel="stylesheet" href="assets/css/main.css" /> -->
    <%= favicon_link_tag 'icon.png' %>
  </head>
    
  <body style="background-color: #fff">
    <div class="admin-bar">
      <ul>
        <li><%= link_to "前台首頁", root_path %></li>
        <li><%= link_to "home", admin_root_path %></li>
        <li><a href="#">About</a></li>
        <li><%= link_to "writing", admin_writings_path %></li>
        <li><a href="#">Contact</a></li>
        <li><%#= link_to "admin_user",admin_user_path %></li>
      </ul>
    </div>
    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I-M HERE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <!-- <link rel="stylesheet" href="assets/css/main.css" /> -->
    <noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
    <%= favicon_link_tag 'icon.png' %>
  </head>
    
  <body class="is-loading">
    <div class="html5up">
      <div id="wrapper" class="fade-in">

        <div id="intro">
          <h1 style="text-transform:none;">I-M here</h1>
          <h1>商業x英文x德文</h1> 
          <p>Try to Do My Best
          </p>
          <ul class="actions">
            <li><a href="#header" class="button icon solo fa-arrow-down scrolly">Continue</a></li>
          </ul>
        </div>

        <header id="header">
          <%= link_to 'Main Page', root_path , class: "logo" %>
        </header>

        <%= yield %>


        <div id="copyright">
          <ul><li>&copy; Untitled I-M HERE 2018</li></ul>
        </div>
      </div>
    </div>
  </body>
</html>